### ISSUE TITLE
Access Token?

### ISSUE THREAD

**Issue by chrisbarber7** [Johnny2Shoes/Owin.Security.Strava#6]
Not sure if I'm confusing Authentication and Authorization?     

I've got a demo app authenticating via Strava but I can't see anyway to access a token for the logged in Strava user to make calls to get activities, etc?

**Comment by msteve123** [comment]
Hey,

It's returned in one of the claims - and can be accessed like:

Claim c = externalIdentity.Claims.First(x => x.Type == "urn:strava:accesstoken");

From within your Method ExternalLoginConfirmation within the AccountController (assuming you created an example app).

Hope that helps!

**Comment by chrisbarber7** [comment]
Thanks.  I can see it now.
